[33mcommit bc2700f2da3824e9149ef4ea05b37ca2b3cf66ca[m[33m ([m[1;36mHEAD -> [m[1;32mmain[m[33m, [m[1;31morigin/main[m[33m)[m
Author: João Pedro Amaral Dias <joaopedrodiasamaral@gmail.com>
Date:   Fri Jan 29 09:20:54 2021 -0300

    first commit

[33mcommit 05d2c2fc922aaf4b2bf0093b5e85ff5d8fdbbcda[m
Author: João Pedro Amaral Dias <joaopedrodiasamaral@gmail.com>
Date:   Thu Jan 28 12:03:32 2021 -0300

    Initial commit from Create Next App
