@baseUrl = http://localhost:3000/api

//	Arquivo restClient contendo todas requisições a api


# @name create_user
POST {{baseUrl}}/user HTTP/1.1
content-type: application/json

{
	"name":"Rafael Neiva",
	"email":"joaopedrodiasamaral@gmail.com",
	"cellphone":"78945678",
    "courses": ["Projeto transversal 2", "BDI", "BDII"],
    "available_hours": {
			"monday":[
				7, 14, 18
			],
			"friday":[
				12, 16, 20
			]
		},
    "available_locations":["online"],
	"teacher": true
}

###

# @name bucando_usuario_by_email

GET {{baseUrl}}/user/gabi@gmail.com1 HTTP/1.1
content-type: application/json


###

# @name show_teacher_profile

GET {{baseUrl}}/teacher/6019ace515fc2837d06a89e6 HTTP/1.1
content-type: application/json

###

# @name find_by_course

GET {{baseUrl}}/search HTTP/1.1
content-type: application/json

{
	"courses":"BDII" 
	//Gabi
}

###

#  @name create_appointment

POST {{baseUrl}}/appointment HTTP/1.1
content-type: application/json

{
	"date": "2021-02-02T19:10:46.753Z",
	"teacher_name": "Luiza",
	"teacher_id": "6019ace515fc2837d06a89e6",
	"student_name":"Gabi",
	"student_id": "6019ade215fc2837d06a89e7",
	"course": "Sistemas Digitais",
	"location": "Cafeteria dos anjos"
}